name: Build and test Jekyll site

on:
  push:
    branches:
      - main  # Set to your default branch, e.g., main or master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.4  # Specify the Ruby version you need for your project

    - name: Build and test Jekyll site
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build
